In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
df= pd.read_csv("Ventas_totales.csv")
df.head(5)

,indice_tiempo,ventas_precios_corrientes,ventas_precios_constantes,ventas_totales_canal_venta,salon_ventas,canales_on_line,ventas_totales_medio_pago,efectivo,tarjetas_debito,tarjetas_credito,...,almacen,panaderia,lacteos,carnes,verduleria_fruteria,alimentos_preparados_rotiseria,articulos_limpieza_perfumeria,indumentaria_calzado_textiles_hogar,electronicos_articulos_hogar,otros
0,01/01/2017,27858.9,27477.3,27858872.08,27591730.13,267141.956,27858872.08,1.023010e+07,6864575.384,9047205.493,...,6705475.318,9.459063e+05,2880656.169,2606192.942,1.050314e+06,340777.3882,4397543.671,772371.8476,1838507.096,2806660.309
1,01/02/2017,25994.2,25223.4,25994200.17,25749179.40,245020.769,25994200.17,9.719067e+06,6438494.011,8309150.301,...,6576624.803,9.256186e+05,2855639.900,2600083.591,1.026167e+06,328288.6951,4053283.771,672290.5165,1257661.903,2354084.901
2,01/03/2017,27780.0,26334.3,27780006.52,27472228.72,307777.804,27780006.52,1.024444e+07,6908522.962,8845010.494,...,7437264.174,1.016148e+06,3188259.169,2824976.726,1.075526e+06,353335.1548,4354197.611,667696.6653,1305674.917,2266189.277
3,01/04/2017,29134.3,27045.9,29134272.22,28827479.49,306792.733,29134272.22,1.031263e+07,7454251.800,9458166.682,...,8211244.093,1.132396e+06,3257140.159,3006158.760,1.037213e+06,359694.4537,4355706.646,838948.2458,1535726.345,2146755.887
4,01/05/2017,27969.0,25631.9,27969004.68,27569311.41,399693.262,27969004.68,1.014761e+07,6735747.319,9220929.862,...,7651058.084,1.033082e+06,3232635.767,2799142.123,9.826512e+05,336568.0085,4206101.605,915895.1498,1824462.036,2117971.483

In [3]:
#Realizamos una copia del dataframe
data1=df.copy()

In [4]:
valores_nulos=data1.isnull().sum()
valores_nulos

indice_tiempo                           0
ventas_precios_corrientes               0
ventas_precios_constantes               0
ventas_totales_canal_venta              0
salon_ventas                            6
canales_on_line                         0
ventas_totales_medio_pago               0
efectivo                                0
tarjetas_debito                         1
tarjetas_credito                        7
otros_medios                            1
ventas_totales_grupo_articulos          0
subtotal_ventas_alimentos_bebidas      10
bebidas                                 1
almacen                                 2
panaderia                               1
lacteos                                 1
carnes                                  1
verduleria_fruteria                     1
alimentos_preparados_rotiseria          1
articulos_limpieza_perfumeria           0
indumentaria_calzado_textiles_hogar     2
electronicos_articulos_hogar            3
otros                                   4
dtype: int64

In [7]:
pd.options.display.max_columns=None

In [8]:
data1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 65 entries, 0 to 64
Data columns (total 24 columns):
 #   Column                               Non-Null Count  Dtype
---  ------                               --------------  -----
 0   indice_tiempo                        65 non-null     object
 1   ventas_precios_corrientes            65 non-null     float64
 2   ventas_precios_constantes            65 non-null     float64
 3   ventas_totales_canal_venta           65 non-null     float64
 4   salon_ventas                         65 non-null     float64
 5   canales_on_line                      65 non-null     float64
 6   ventas_totales_medio_pago            65 non-null     float64
 7   efectivo                             65 non-null     float64
 8   tarjetas_debito                      64 non-null     float64
 9   tarjetas_credito                     58 non-null     float64
 10  otros_medios                         64 non-null     float64
 11  ventas_totales_grupo_articulos       65 non-null     float64
 12  subtotal_ventas_alimentos_bebidas    55 non-null     float64
 13  bebidas                              64 non-null     float64
 14  almacen                              63 non-null     float64
 15  panaderia                            64 non-null     float64
 16  lacteos                              64 non-null     float64
 17  carnes                               64 non-null     float64
 18  verduleria_fruteria                  64 non-null     float64
 19  alimentos_preparados_rotiseria       64 non-null     float64
 20  articulos_limpieza_perfumeria        65 non-null     float64
 21  indumentaria_calzado_textiles_hogar  63 non-null     float64
 22  electronicos_articulos_hogar         62 non-null     float64
 23  otros                                61 non-null     float64
dtypes: float64(23), object(1)
memory usage: 12.3+ KB

In [9]:
data1.head(10)

,indice_tiempo,ventas_precios_corrientes,ventas_precios_constantes,ventas_totales_canal_venta,salon_ventas,canales_on_line,ventas_totales_medio_pago,efectivo,tarjetas_debito,tarjetas_credito,otros_medios,ventas_totales_grupo_articulos,subtotal_ventas_alimentos_bebidas,bebidas,almacen,panaderia,lacteos,carnes,verduleria_fruteria,alimentos_preparados_rotiseria,articulos_limpieza_perfumeria,indumentaria_calzado_textiles_hogar,electronicos_articulos_hogar,otros
0,01/01/2017,27858.9,27477.3,27858872.08,27591730.13,267141.9560,27858872.08,1.023010e+07,6864575.384,9.047205e+06,1716991.073,27858872.08,18043789.16,3514467.398,6705475.318,9.459063e+05,2880656.169,2606192.942,1.050314e+06,340777.3882,4397543.671,7.723718e+05,1838507.096,2806660.309
1,01/02/2017,25994.2,25223.4,25994200.17,25749179.40,245020.7690,25994200.17,9.719067e+06,6438494.011,8.309150e+06,1527488.518,25994200.17,17656879.08,3344456.931,6576624.803,9.256186e+05,2855639.900,2600083.591,1.026167e+06,328288.6951,4053283.771,6.722905e+05,1257661.903,2354084.901
2,01/03/2017,27780.0,26334.3,27780006.52,27472228.72,307777.8040,27780006.52,1.024444e+07,6908522.962,8.845010e+06,1782030.557,27780006.52,19186248.05,3290739.324,7437264.174,1.016148e+06,3188259.169,2824976.726,1.075526e+06,353335.1548,4354197.611,6.676967e+05,1305674.917,2266189.277
3,01/04/2017,29134.3,27045.9,29134272.22,28827479.49,306792.7330,29134272.22,1.031263e+07,7454251.800,9.458167e+06,1909221.374,29134272.22,20257135.10,3253288.237,8211244.093,1.132396e+06,3257140.159,3006158.760,1.037213e+06,359694.4537,4355706.646,8.389482e+05,1535726.345,2146755.887
4,01/05/2017,27969.0,25631.9,27969004.68,27569311.41,399693.2620,27969004.68,1.014761e+07,6735747.319,9.220930e+06,1864714.157,27969004.68,18904574.40,2869437.411,7651058.084,1.033082e+06,3232635.767,2799142.123,9.826512e+05,336568.0085,4206101.605,9.158951e+05,1824462.036,2117971.483
5,01/06/2017,29132.7,26365.4,29132712.74,28763865.42,368847.3260,29132712.74,1.056549e+07,7337456.597,9.196110e+06,2033652.189,29132712.74,19601615.80,3103589.599,7911936.245,1.083494e+06,3322049.564,2883228.762,9.522033e+05,345114.1199,4277889.539,1.001572e+06,1893542.062,2358093.345
6,01/07/2017,31182.3,27819.4,31182302.46,30815311.77,366990.6830,31182302.46,1.090591e+07,8183012.318,1.016290e+07,1930477.521,31182302.46,20882660.95,3325398.656,8482567.662,1.153102e+06,3534096.704,3013143.968,9.943436e+05,380008.1679,4599798.334,1.026743e+06,1995091.144,2678008.532
7,01/08/2017,31154.9,27394.1,31154880.94,30763355.89,391525.0520,31154880.94,1.104163e+07,7899351.017,NaN,2098727.771,31154880.94,20666687.82,3261204.283,8275620.180,1.147970e+06,3604272.106,2946950.822,1.060479e+06,370191.1923,4585003.764,7.864155e+05,1882133.804,3234640.071
8,01/09/2017,30521.5,26404.3,30521506.20,30135595.70,385910.4980,30521506.20,1.078917e+07,7888243.177,9.795879e+06,2048214.044,30521506.20,21025932.94,3488952.968,8319868.332,1.144159e+06,3640337.038,2991425.025,1.078616e+06,362573.6633,4708171.561,7.405727e+05,1673423.550,NaN
9,01/10/2017,32446.0,27766.7,32445983.01,31980223.91,465759.1013,32445983.01,1.122031e+07,8695476.803,1.144746e+07,1082741.605,32445983.01,21743902.23,3928861.098,NaN,1.171283e+06,3698962.630,3091846.913,1.147860e+06,381176.1241,4889144.438,8.704811e+05,2404158.327,2538296.932

In [10]:
data1["salon_ventas"] =data1["salon_ventas"].fillna(0)

In [ ]:
data1["Superficie"]=data1["Superficie"].fillna(round(data2["Superficie"].mean(),1))